In [191]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.1.3)

In [3]:
import pandas as pd
import numpy as np

In [4]:
#read in the uber dataset 
df1=pd.read_csv("uber.csv")

In [5]:
df1.info()
df1.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         200000 non-null  int64
 1   key                200000 non-null  object
 2   fare_amount        200000 non-null  float64
 3   pickup_datetime    200000 non-null  object
 4   pickup_longitude   200000 non-null  float64
 5   pickup_latitude    200000 non-null  float64
 6   dropoff_longitude  199999 non-null  float64
 7   dropoff_latitude   199999 non-null  float64
 8   passenger_count    200000 non-null  int64
dtypes: float64(5), int64(2), object(2)
memory usage: 13.7+ MB

,Unnamed: 0,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,2.000000e+05,200000.000000,200000.000000,200000.000000,199999.000000,199999.000000,200000.000000
mean,2.771250e+07,11.359955,-72.527638,39.935885,-72.525292,39.923890,1.684535
std,1.601382e+07,9.901776,11.437787,7.720539,13.117408,6.794829,1.385997
min,1.000000e+00,-52.000000,-1340.648410,-74.015515,-3356.666300,-881.985513,0.000000
25%,1.382535e+07,6.000000,-73.992065,40.734796,-73.991407,40.733823,1.000000
50%,2.774550e+07,8.500000,-73.981823,40.752592,-73.980093,40.753042,1.000000
75%,4.155530e+07,12.500000,-73.967153,40.767158,-73.963659,40.768001,2.000000
max,5.542357e+07,499.000000,57.418457,1644.421482,1153.572603,872.697628,208.000000

In [6]:
#the first column: Unname:0 is just a junk column so I will remove it. Additionally, the 'key' column also lacks purpose.
df1.rename(columns={'Unnamed: 0': 'Unnamed'},inplace=True)
df1.drop(columns=['Unnamed'], axis=1,inplace=True)
df1.drop(columns=['key'],axis=1,inplace=True)
df1.columns

Index(['fare_amount', 'pickup_datetime', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count'],
      dtype='object')

In [8]:
#checked that there were only 2 incidents of NaN values, so I decided to drop the rows.
df1.head()
df1.isnull().sum()
df1=df1.dropna()

In [19]:

#Fare Amount must not be negative
df1=df1[(df1['fare_amount']>0)
# longitude values must be within -180 and +180
&(df1['pickup_longitude'].between(-180,180))
&(df1['dropoff_longitude'].between(-180,180))
#Latitude values must be within -90 and +90
&(df1['pickup_latitude'].between(-90,90))
&(df1['dropoff_latitude'].between(-90,90))
#passenger count must not be 0
&(df1['passenger_count']>0)]
df1.describe()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,199257.000000,199257.000000,199257.000000,199257.000000,199257.000000,199257.000000
mean,11.369377,-72.504180,39.919176,-72.514415,39.923488,1.690475
std,9.905961,10.442217,6.127742,10.403018,6.114291,1.384788
min,0.010000,-93.824668,-74.015515,-75.458979,-74.015750,1.000000
25%,6.000000,-73.992063,40.734795,-73.991409,40.733828,1.000000
50%,8.500000,-73.981824,40.752583,-73.980094,40.753042,1.000000
75%,12.500000,-73.967160,40.767155,-73.963663,40.767995,2.000000
max,499.000000,40.808425,48.018760,40.831932,45.031598,208.000000

In [25]:
#the dateTime column was converted to the dateTime format  
df1['pickup_datetime']=pd.to_datetime(df1['pickup_datetime'])
#new columns are made for future model usage
df1['hour'] = df1['pickup_datetime'].dt.hour
df1['day_of_week'] = df1['pickup_datetime'].dt.dayofweek
df1['month'] = df1['pickup_datetime'].dt.month
df1['year'] = df1['pickup_datetime'].dt.year
# dropping the "pickup_datetime" column as it serves no purpose now.
df1=df1.drop('pickup_datetime',axis=1)

In [28]:
df1.info()
df1.describe()
df1.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 199257 entries, 0 to 199999
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   fare_amount        199257 non-null  float64
 1   pickup_longitude   199257 non-null  float64
 2   pickup_latitude    199257 non-null  float64
 3   dropoff_longitude  199257 non-null  float64
 4   dropoff_latitude   199257 non-null  float64
 5   passenger_count    199257 non-null  int64
 6   hour               199257 non-null  int32
 7   day_of_week        199257 non-null  int32
 8   month              199257 non-null  int32
 9   year               199257 non-null  int32
dtypes: float64(5), int32(4), int64(1)
memory usage: 13.7 MB

fare_amount          0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    0
dropoff_latitude     0
passenger_count      0
hour                 0
day_of_week          0
month                0
year                 0
dtype: int64